on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Show env vars & secrets values
        run: |
          echo "Var: ${{ env.MY_ENV_VAR }}" >> file
          echo "Secret: ${{ secrets.MY_SECRET }}" >> file
          echo file
