on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    environment: uat
    steps:
      - name: Show env vars & secrets values
        run: |
          echo "Env: 
          echo "Var: $MY_ENV_VAR" >> file
          echo "Secret: $MY_SECRET" >> file
          cat file
        env:
          MY_ENV_VAR: ${{ env.MY_ENV_VAR }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
